In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from dotenv import load_dotenv
import os

import warnings
warnings.filterwarnings("ignore")

In [23]:
load_dotenv('.env')

True

In [15]:
api_key = os.getenv("EASYDATA_API_KEY")
api_url = os.getenv("EASYDATA_API_URL")

In [24]:
from quantec.easydata.client import Client
# All parameters and defaults
client = Client(
    api_key= api_key,  # default: uses EASYDATA_API_KEY env var
    api_url= api_url,  # default: EASYDATA_API_URL or "https://www.easydata.co.za/api/v3"
    use_cache=True,
    cache_dir="cache",
)

In [56]:
pk = """
SAPS-E_P9-S_LIC01S00-C_T
SAPS-E_P9-S_LIC01S00-C_S
SAPS-E_P9-S_LIC01S00-C_SR
SAPS-E_P9-S_LIC01S00-C_SRC
SAPS-E_P9-S_LIC01S00-C_SRCM
SAPS-E_P9-S_LIC01S00-C_SRCS
SAPS-E_P9-S_LIC01S00-C_SRCSQ
SAPS-E_P9-S_LIC01S00-C_SRCSC
SAPS-E_P9-S_LIC01S00-C_SRCSB
SAPS-E_P9-S_LIC01S00-C_SRCSR
SAPS-E_P9-S_LIC01S00-C_SRCSA
SAPS-E_P9-S_LIC01S00-C_SRCSD
SAPS-E_P9-S_LIC01S00-C_SRCSI
SAPS-E_P9-S_LIC01S00-C_SRCSS
SAPS-E_P9-S_LIC01S00-C_SRCL
SAPS-E_P9-S_LIC01S00-C_SRCH
SAPS-E_P9-S_LIC01S00-C_SRCA
SAPS-E_P9-S_LIC01S00-C_SRCR
SAPS-E_P9-S_LIC01S00-C_SRCX
SAPS-E_P9-S_LIC01S00-C_SRCXS
SAPS-E_P9-S_LIC01S00-C_SRCXR
SAPS-E_P9-S_LIC01S00-C_SRCXB
SAPS-E_P9-S_LIC01S00-C_SRCXC
SAPS-E_P9-S_LIC01S00-C_SRCXO
SAPS-E_P9-S_LIC01S00-C_SRCX3
SAPS-E_P9-S_LIC01S00-C_SRCX3B
SAPS-E_P9-S_LIC01S00-C_SRCX3R
SAPS-E_P9-S_LIC01S00-C_SRCX3C
SAPS-E_P9-S_LIC01S00-C_SRCXT
SAPS-E_P9-S_LIC01S00-C_SRR
SAPS-E_P9-S_LIC01S00-C_SRRA
SAPS-E_P9-S_LIC01S00-C_SRRP
SAPS-E_P9-S_LIC01S00-C_SRP
SAPS-E_P9-S_LIC01S00-C_SRPR
SAPS-E_P9-S_LIC01S00-C_SRPB
SAPS-E_P9-S_LIC01S00-C_SRPV
SAPS-E_P9-S_LIC01S00-C_SRPF
SAPS-E_P9-S_LIC01S00-C_SRPS
SAPS-E_P9-S_LIC01S00-C_SRO
SAPS-E_P9-S_LIC01S00-C_SROO
SAPS-E_P9-S_LIC01S00-C_SROC
SAPS-E_P9-S_LIC01S00-C_SROS
SAPS-E_P9-S_LIC01S00-C_SD
SAPS-E_P9-S_LIC01S00-C_SDF
SAPS-E_P9-S_LIC01S00-C_SDN
SAPS-E_P9-S_LIC01S00-C_SDD
SAPS-E_P9-S_LIC01S00-C_SDS
SAPS-E_P9-S_LIC01S00-C_O
SAPS-E_P9-S_LIC01S00-C_OH
SAPS-E_P9-S_LIC01S00-C_OV
SAPS-E_P9-S_LIC01S00-C_OC
SAPS-E_P9-S_LIC01S00-C_ON
SAPS-E_P9-S_LIC01S00-C_OK
SAPS-E_P9-S_LIC02S00-C_T
SAPS-E_P9-S_LIC02S00-C_S
SAPS-E_P9-S_LIC02S00-C_SR
SAPS-E_P9-S_LIC02S00-C_SRC
SAPS-E_P9-S_LIC02S00-C_SRCM
SAPS-E_P9-S_LIC02S00-C_SRCS
SAPS-E_P9-S_LIC02S00-C_SRCSQ
SAPS-E_P9-S_LIC02S00-C_SRCSC
SAPS-E_P9-S_LIC02S00-C_SRCSB
SAPS-E_P9-S_LIC02S00-C_SRCSR
SAPS-E_P9-S_LIC02S00-C_SRCSA
SAPS-E_P9-S_LIC02S00-C_SRCSD
SAPS-E_P9-S_LIC02S00-C_SRCSI
SAPS-E_P9-S_LIC02S00-C_SRCSS
SAPS-E_P9-S_LIC02S00-C_SRCL
SAPS-E_P9-S_LIC02S00-C_SRCH
SAPS-E_P9-S_LIC02S00-C_SRCA
SAPS-E_P9-S_LIC02S00-C_SRCR
SAPS-E_P9-S_LIC02S00-C_SRCX
SAPS-E_P9-S_LIC02S00-C_SRCXS
SAPS-E_P9-S_LIC02S00-C_SRCXR
SAPS-E_P9-S_LIC02S00-C_SRCXB
SAPS-E_P9-S_LIC02S00-C_SRCXC
SAPS-E_P9-S_LIC02S00-C_SRCXO
SAPS-E_P9-S_LIC02S00-C_SRCX3
SAPS-E_P9-S_LIC02S00-C_SRCX3B
SAPS-E_P9-S_LIC02S00-C_SRCX3R
SAPS-E_P9-S_LIC02S00-C_SRCX3C
SAPS-E_P9-S_LIC02S00-C_SRCXT
SAPS-E_P9-S_LIC02S00-C_SRR
SAPS-E_P9-S_LIC02S00-C_SRRA
SAPS-E_P9-S_LIC02S00-C_SRRP
SAPS-E_P9-S_LIC02S00-C_SRP
SAPS-E_P9-S_LIC02S00-C_SRPR
SAPS-E_P9-S_LIC02S00-C_SRPB
SAPS-E_P9-S_LIC02S00-C_SRPV
SAPS-E_P9-S_LIC02S00-C_SRPF
SAPS-E_P9-S_LIC02S00-C_SRPS
SAPS-E_P9-S_LIC02S00-C_SRO
SAPS-E_P9-S_LIC02S00-C_SROO
SAPS-E_P9-S_LIC02S00-C_SROC
SAPS-E_P9-S_LIC02S00-C_SROS
SAPS-E_P9-S_LIC02S00-C_SD
SAPS-E_P9-S_LIC02S00-C_SDF
SAPS-E_P9-S_LIC02S00-C_SDN
SAPS-E_P9-S_LIC02S00-C_SDD
SAPS-E_P9-S_LIC02S00-C_SDS
SAPS-E_P9-S_LIC02S00-C_O
SAPS-E_P9-S_LIC02S00-C_OH
SAPS-E_P9-S_LIC02S00-C_OV
SAPS-E_P9-S_LIC02S00-C_OC
SAPS-E_P9-S_LIC02S00-C_ON
SAPS-E_P9-S_LIC02S00-C_OK
SAPS-E_P9-S_LIC03S00-C_T
SAPS-E_P9-S_LIC03S00-C_S
SAPS-E_P9-S_LIC03S00-C_SR
SAPS-E_P9-S_LIC03S00-C_SRC
SAPS-E_P9-S_LIC03S00-C_SRCM
SAPS-E_P9-S_LIC03S00-C_SRCS
SAPS-E_P9-S_LIC03S00-C_SRCSQ
SAPS-E_P9-S_LIC03S00-C_SRCSC
SAPS-E_P9-S_LIC03S00-C_SRCSB
SAPS-E_P9-S_LIC03S00-C_SRCSR
SAPS-E_P9-S_LIC03S00-C_SRCSA
SAPS-E_P9-S_LIC03S00-C_SRCSD
SAPS-E_P9-S_LIC03S00-C_SRCSI
SAPS-E_P9-S_LIC03S00-C_SRCSS
SAPS-E_P9-S_LIC03S00-C_SRCL
SAPS-E_P9-S_LIC03S00-C_SRCH
SAPS-E_P9-S_LIC03S00-C_SRCA
SAPS-E_P9-S_LIC03S00-C_SRCR
SAPS-E_P9-S_LIC03S00-C_SRCX
SAPS-E_P9-S_LIC03S00-C_SRCXS
SAPS-E_P9-S_LIC03S00-C_SRCXR
SAPS-E_P9-S_LIC03S00-C_SRCXB
SAPS-E_P9-S_LIC03S00-C_SRCXC
SAPS-E_P9-S_LIC03S00-C_SRCXO
SAPS-E_P9-S_LIC03S00-C_SRCX3
SAPS-E_P9-S_LIC03S00-C_SRCX3B
SAPS-E_P9-S_LIC03S00-C_SRCX3R
SAPS-E_P9-S_LIC03S00-C_SRCX3C
SAPS-E_P9-S_LIC03S00-C_SRCXT
SAPS-E_P9-S_LIC03S00-C_SRR
SAPS-E_P9-S_LIC03S00-C_SRRA
SAPS-E_P9-S_LIC03S00-C_SRRP
SAPS-E_P9-S_LIC03S00-C_SRP
SAPS-E_P9-S_LIC03S00-C_SRPR
SAPS-E_P9-S_LIC03S00-C_SRPB
SAPS-E_P9-S_LIC03S00-C_SRPV
SAPS-E_P9-S_LIC03S00-C_SRPF
SAPS-E_P9-S_LIC03S00-C_SRPS
SAPS-E_P9-S_LIC03S00-C_SRO
SAPS-E_P9-S_LIC03S00-C_SROO
SAPS-E_P9-S_LIC03S00-C_SROC
SAPS-E_P9-S_LIC03S00-C_SROS
SAPS-E_P9-S_LIC03S00-C_SD
SAPS-E_P9-S_LIC03S00-C_SDF
SAPS-E_P9-S_LIC03S00-C_SDN
SAPS-E_P9-S_LIC03S00-C_SDD
SAPS-E_P9-S_LIC03S00-C_SDS
SAPS-E_P9-S_LIC03S00-C_O
SAPS-E_P9-S_LIC03S00-C_OH
SAPS-E_P9-S_LIC03S00-C_OV
SAPS-E_P9-S_LIC03S00-C_OC
SAPS-E_P9-S_LIC03S00-C_ON
SAPS-E_P9-S_LIC03S00-C_OK
SAPS-E_P9-S_LIC04S00-C_T
SAPS-E_P9-S_LIC04S00-C_S
SAPS-E_P9-S_LIC04S00-C_SR
SAPS-E_P9-S_LIC04S00-C_SRC
SAPS-E_P9-S_LIC04S00-C_SRCM
SAPS-E_P9-S_LIC04S00-C_SRCS
SAPS-E_P9-S_LIC04S00-C_SRCSQ
SAPS-E_P9-S_LIC04S00-C_SRCSC
SAPS-E_P9-S_LIC04S00-C_SRCSB
SAPS-E_P9-S_LIC04S00-C_SRCSR
SAPS-E_P9-S_LIC04S00-C_SRCSA
SAPS-E_P9-S_LIC04S00-C_SRCSD
SAPS-E_P9-S_LIC04S00-C_SRCSI
SAPS-E_P9-S_LIC04S00-C_SRCSS
SAPS-E_P9-S_LIC04S00-C_SRCL
SAPS-E_P9-S_LIC04S00-C_SRCH
SAPS-E_P9-S_LIC04S00-C_SRCA
SAPS-E_P9-S_LIC04S00-C_SRCR
SAPS-E_P9-S_LIC04S00-C_SRCX
SAPS-E_P9-S_LIC04S00-C_SRCXS
SAPS-E_P9-S_LIC04S00-C_SRCXR
SAPS-E_P9-S_LIC04S00-C_SRCXB
SAPS-E_P9-S_LIC04S00-C_SRCXC
SAPS-E_P9-S_LIC04S00-C_SRCXO
SAPS-E_P9-S_LIC04S00-C_SRCX3
SAPS-E_P9-S_LIC04S00-C_SRCX3B
SAPS-E_P9-S_LIC04S00-C_SRCX3R
SAPS-E_P9-S_LIC04S00-C_SRCX3C
SAPS-E_P9-S_LIC04S00-C_SRCXT
SAPS-E_P9-S_LIC04S00-C_SRR
SAPS-E_P9-S_LIC04S00-C_SRRA
SAPS-E_P9-S_LIC04S00-C_SRRP
SAPS-E_P9-S_LIC04S00-C_SRP
SAPS-E_P9-S_LIC04S00-C_SRPR
SAPS-E_P9-S_LIC04S00-C_SRPB
SAPS-E_P9-S_LIC04S00-C_SRPV
SAPS-E_P9-S_LIC04S00-C_SRPF
SAPS-E_P9-S_LIC04S00-C_SRPS
SAPS-E_P9-S_LIC04S00-C_SRO
SAPS-E_P9-S_LIC04S00-C_SROO
SAPS-E_P9-S_LIC04S00-C_SROC
SAPS-E_P9-S_LIC04S00-C_SROS
SAPS-E_P9-S_LIC04S00-C_SD
SAPS-E_P9-S_LIC04S00-C_SDF
SAPS-E_P9-S_LIC04S00-C_SDN
SAPS-E_P9-S_LIC04S00-C_SDD
SAPS-E_P9-S_LIC04S00-C_SDS
SAPS-E_P9-S_LIC04S00-C_O
SAPS-E_P9-S_LIC04S00-C_OH
SAPS-E_P9-S_LIC04S00-C_OV
SAPS-E_P9-S_LIC04S00-C_OC
SAPS-E_P9-S_LIC04S00-C_ON
SAPS-E_P9-S_LIC04S00-C_OK
"""

In [105]:
# Get time series data (CSV format only)
data = client.get_data(time_series_codes=pk)
data.head()

,title,unit,source,code,date,value
0,P9: Limpopo — LIC01S00: Bela Bela Cluster — T:...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_T-CAN,1995-12-31,4967.099581
1,P9: Limpopo — LIC01S00: Bela Bela Cluster — T:...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_T-CAN,1996-12-31,5009.190684
2,P9: Limpopo — LIC01S00: Bela Bela Cluster — T:...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_T-CAN,1997-12-31,5387.745231
3,P9: Limpopo — LIC01S00: Bela Bela Cluster — T:...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_T-CAN,1998-12-31,5627.984961
4,P9: Limpopo — LIC01S00: Bela Bela Cluster — T:...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_T-CAN,1999-12-31,5880.399697

In [64]:
data.tail()

,title,unit,source,code,date,value
1585,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2020-12-31,7.045384
1586,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2021-12-31,5.029921
1587,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2022-12-31,6.036532
1588,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2023-12-31,11.066564
1589,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2024-12-31,20.116818

In [67]:
data["date"] = pd.to_datetime(data["date"])

In [73]:
import numpy as np
data["value"] = np.floor(data['value']).astype('Int64')

In [60]:
data["date"].unique()

<DatetimeArray>
['1995-12-31 00:00:00', '1996-12-31 00:00:00', '1997-12-31 00:00:00',
 '1998-12-31 00:00:00', '1999-12-31 00:00:00', '2000-12-31 00:00:00',
 '2001-12-31 00:00:00', '2002-12-31 00:00:00', '2003-12-31 00:00:00',
 '2004-12-31 00:00:00', '2005-12-31 00:00:00', '2006-12-31 00:00:00',
 '2007-12-31 00:00:00', '2008-12-31 00:00:00', '2009-12-31 00:00:00',
 '2010-12-31 00:00:00', '2011-12-31 00:00:00', '2012-12-31 00:00:00',
 '2013-12-31 00:00:00', '2014-12-31 00:00:00', '2015-12-31 00:00:00',
 '2016-12-31 00:00:00', '2017-12-31 00:00:00', '2018-12-31 00:00:00',
 '2019-12-31 00:00:00', '2020-12-31 00:00:00', '2021-12-31 00:00:00',
 '2022-12-31 00:00:00', '2023-12-31 00:00:00', '2024-12-31 00:00:00']
Length: 30, dtype: datetime64[ns]

In [61]:
data.shape

(1590, 6)

In [76]:
data.tail()

,title,unit,source,code,date,value
1585,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2020-12-31,7
1586,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2021-12-31,5
1587,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2022-12-31,6
1588,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2023-12-31,11
1589,P9: Limpopo — LIC01S00: Bela Bela Cluster — OK...,Number of recorded crimes (custom of Monthly V...,South African Police Service; Quantec,SAPS-E_P9-S_LIC01S00-C_OK-CAN,2024-12-31,20

* Read in Datasets

In [3]:
df1 = pd.read_excel("C:/Users/amare/OneDrive/Desktop/Pycharm practice/datasets/1st Batch.xlsx", sheet_name="Monthly")
df2 = pd.read_excel("C:/Users/amare/OneDrive/Desktop/Pycharm practice/datasets/2nd Batch.xlsx", sheet_name="Monthly")
df3 = pd.read_excel("C:/Users/amare/OneDrive/Desktop/Pycharm practice/datasets/3rd Batch.xlsx", sheet_name="Monthly")

In [4]:
def preprocess(df):
    df = df[4:]
    df = df.drop(range(5, 8))
    df.columns = df.iloc[0]
    df = df.iloc[1:]
    df = df.rename(columns={'title': 'Date'})
    df = df.set_index("Date")
    df.index = pd.to_datetime(df.index)

    return df

In [124]:
df1 = preprocess(df1)
df2 = preprocess(df2)
df3 = preprocess(df3)

In [125]:
def impute_missing(df):
        df = df.fillna(0)
        df = df.round(0).astype('Int64')
        return df

In [126]:
df1 = impute_missing(df1)
df2 = impute_missing(df2)
df3 = impute_missing(df3)

Impute missing values

In [100]:
df3

4,P9: Limpopo — LIC10S00: Modimolle Cluster — T: 25 Serious and Other crimes,P9: Limpopo — LIC10S00: Modimolle Cluster — S: 20 Serious crimes,P9: Limpopo — LIC10S00: Modimolle Cluster — SR: 17 Community reported Serious crimes,P9: Limpopo — LIC10S00: Modimolle Cluster — SRC: Contact crimes (Crimes against the person),P9: Limpopo — LIC10S00: Modimolle Cluster — SRCM: Murder,P9: Limpopo — LIC10S00: Modimolle Cluster — SRCS: Sexual Offences (also see SDS),P9: Limpopo — LIC10S00: Modimolle Cluster — SRCSQ: Attempted sexual offences,P9: Limpopo — LIC10S00: Modimolle Cluster — SRCSC: Contact sexual offences,P9: Limpopo — LIC10S00: Modimolle Cluster — SRCSB: Abduction,P9: Limpopo — LIC10S00: Modimolle Cluster — SRCSR: Rape,...,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDF: Illegal possession of firearms and ammunition,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDN: Drug-related crime,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDD: Driving under the influence of alcohol or drugs,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDS: Sexual Offences detected as a result of police action,P9: Limpopo — LIC13S00: Tzaneen Cluster — O: Other crime categories,P9: Limpopo — LIC13S00: Tzaneen Cluster — OH: Culpable homicide,P9: Limpopo — LIC13S00: Tzaneen Cluster — OV: Public violence,P9: Limpopo — LIC13S00: Tzaneen Cluster — OC: Crimen injuria,P9: Limpopo — LIC13S00: Tzaneen Cluster — ON: Neglect and ill-treatment of children,P9: Limpopo — LIC13S00: Tzaneen Cluster — OK: Kidnapping
Date,,,,,,,,,,,,,,,,,,,,,
2001-01-31,453,421,416,150,0,14,0,0,0,0,...,3,23,13,0,91,8,0,79,1,3
2001-02-28,460,416,411,178,1,9,0,0,0,0,...,2,12,7,0,79,5,0,66,1,6
2001-03-31,537,500,495,219,3,12,0,0,0,0,...,4,1,4,0,92,12,0,71,3,5
2001-04-30,479,441,431,169,3,8,0,0,0,0,...,10,10,3,0,100,8,0,85,5,2
2001-05-31,464,445,436,135,1,6,0,0,0,0,...,7,16,1,0,56,5,0,46,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-31,277,256,195,63,0,18,0,0,0,15,...,8,67,33,44,21,8,0,6,1,6
2025-06-30,272,264,180,59,0,16,2,1,0,11,...,5,100,35,74,33,13,0,11,2,7
2025-07-31,279,263,177,49,0,8,0,0,0,6,...,4,84,37,60,26,10,0,10,0,6
2025-08-31,310,297,205,60,0,9,0,0,0,6,...,7,62,34,60,41,12,0,15,3,11
2025-09-30,264,255,176,68,0,13,0,0,0,13,...,6,66,30,46,31,8,1,13,3,6

In [127]:
data = df1.merge(df2, left_index=True, right_index=True, how='outer').merge(df3, left_index=True, right_index=True, how='outer')

Index([2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       ...
       2024, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025, 2025],
      dtype='int32', name='Date', length=297)

In [129]:
data['Year'] = data.index.year
data

4,P9: Limpopo — LIC01S00: Bela Bela Cluster — T: 25 Serious and Other crimes,P9: Limpopo — LIC01S00: Bela Bela Cluster — S: 20 Serious crimes,P9: Limpopo — LIC01S00: Bela Bela Cluster — SR: 17 Community reported Serious crimes,P9: Limpopo — LIC01S00: Bela Bela Cluster — SRC: Contact crimes (Crimes against the person),P9: Limpopo — LIC01S00: Bela Bela Cluster — SRCM: Murder,P9: Limpopo — LIC01S00: Bela Bela Cluster — SRCS: Sexual Offences (also see SDS),P9: Limpopo — LIC01S00: Bela Bela Cluster — SRCSQ: Attempted sexual offences,P9: Limpopo — LIC01S00: Bela Bela Cluster — SRCSC: Contact sexual offences,P9: Limpopo — LIC01S00: Bela Bela Cluster — SRCSB: Abduction,P9: Limpopo — LIC01S00: Bela Bela Cluster — SRCSR: Rape,...,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDN: Drug-related crime,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDD: Driving under the influence of alcohol or drugs,P9: Limpopo — LIC13S00: Tzaneen Cluster — SDS: Sexual Offences detected as a result of police action,P9: Limpopo — LIC13S00: Tzaneen Cluster — O: Other crime categories,P9: Limpopo — LIC13S00: Tzaneen Cluster — OH: Culpable homicide,P9: Limpopo — LIC13S00: Tzaneen Cluster — OV: Public violence,P9: Limpopo — LIC13S00: Tzaneen Cluster — OC: Crimen injuria,P9: Limpopo — LIC13S00: Tzaneen Cluster — ON: Neglect and ill-treatment of children,P9: Limpopo — LIC13S00: Tzaneen Cluster — OK: Kidnapping,Year
Date,,,,,,,,,,,,,,,,,,,,,
2001-01-31,567,532,514,209,4,19,0,0,0,0,...,23,13,0,91,8,0,79,1,3,2001
2001-02-28,472,443,424,162,2,11,0,0,0,0,...,12,7,0,79,5,0,66,1,6,2001
2001-03-31,593,555,540,227,2,22,0,0,0,0,...,1,4,0,92,12,0,71,3,5,2001
2001-04-30,540,515,501,204,2,14,0,0,0,0,...,10,3,0,100,8,0,85,5,2,2001
2001-05-31,519,486,472,177,5,12,0,0,0,0,...,16,1,0,56,5,0,46,0,5,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-31,455,442,377,97,2,7,0,0,0,5,...,67,33,44,21,8,0,6,1,6,2025
2025-06-30,418,400,297,90,3,10,0,0,0,8,...,100,35,74,33,13,0,11,2,7,2025
2025-07-31,431,416,294,85,0,4,0,0,0,3,...,84,37,60,26,10,0,10,0,6,2025
2025-08-31,523,507,354,106,2,12,0,0,0,9,...,62,34,60,41,12,0,15,3,11,2025
2025-09-30,447,432,342,131,1,10,1,1,0,7,...,66,30,46,31,8,1,13,3,6,2025

Concat/ Join 1st, 2nd and 3rd batch on index. make date the index